src/java/Controller/AdopcionController.java
package Controller;

import Entity.Adopcion;
import Controller.util.JsfUtil;
import Controller.util.PaginationHelper;
import Entity.Usuario;
import Session.AdopcionFacade;

import org.primefaces.event.CloseEvent;
import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.servlet.http.HttpServletRequest;

@Named("adopcionController")
@SessionScoped
public class AdopcionController implements Serializable {

    private Adopcion current;
    private DataModel items = null;
    @EJB
    private Session.AdopcionFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public AdopcionController() {
    }

    public Adopcion getSelected() {
        if (current == null) {
            current = new Adopcion();
            selectedItemIndex = -1;
        }
        return current;
    }

    private AdopcionFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Adopcion) getItems().getRowData();
        //selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        selectedItemIndex= -1;
              System.out.println("Nombre "+getSelected().getMascotasIdmascotas().getNombre());
        return "sisexp/catalogo";
    }

    public String prepareCreate() {
//         current = new Adopcion();
         System.out.println(current.getAdoptanteidAdoptante().getUsuarioIdusuario().getNombre());
//        selectedItemIndex = -1;
        Usuario usuario = (Usuario) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("usuario");
        System.out.println(usuario.getIdusuario());
        System.out.println(getSelected().getMascotasIdmascotas().getNombre());
        
        return "expedientes/Create";
    }

    public void metodo(){
        Usuario usuario = (Usuario) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("usuario");
        System.out.println(usuario.getIdusuario());
        System.out.println(getSelected().getMascotasIdmascotas().getNombre());
        
    }
    
    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AdopcionCreated"));
//            String nombreadoptante = current.getAdoptanteidAdoptante()

            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Adopcion) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AdopcionUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Adopcion) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AdopcionDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Adopcion getAdopcion(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Adopcion.class)
    public static class AdopcionControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            AdopcionController controller = (AdopcionController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "adopcionController");
            return controller.getAdopcion(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Adopcion) {
                Adopcion o = (Adopcion) object;
                return getStringKey(o.getIdadopcion());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Adopcion.class.getName());
            }
        }

    }

    public boolean Adoptado(int i) {

        return i == 1;
    }

    public void AdoptaSelect() {

        current = (Adopcion) getItems().getRowData();
        System.out.println("Select");
        System.out.println(current.getResultado());
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        System.out.println(selectedItemIndex);

    }

    public String Adopta() {

        addMessage("Mascota en Adopcion:  Adopcion Registrada", "Adopcion Registrada");
        current = (Adopcion) getItems().getRowData();
        System.out.println(current.getResultado());
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        System.out.println(selectedItemIndex);
        current.setAdopcionAprobada(1);
        try {
            getFacade().edit(current);

        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }

        return "admin";
    }

    public void addMessage(String summary, String detail) {
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, summary, detail);
        FacesContext.getCurrentInstance().addMessage(null, message);

    }

}

web/adopcion/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">


    <body>
    
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                  <h:outputLabel value="#{bundle.CreateAdopcionLabel_resultado}" for="resultado" />
                    <h:inputText id="resultado" value="#{adopcionController.selected.resultado}" title="#{bundle.CreateAdopcionTitle_resultado}" required="true" requiredMessage="#{bundle.CreateAdopcionRequiredMessage_resultado}"/>
                    <h:outputLabel value="#{bundle.CreateAdopcionLabel_adopcionAprobada}" for="adopcionAprobada" />
                    <h:inputText id="adopcionAprobada" value="#{adopcionController.selected.adopcionAprobada}" title="#{bundle.CreateAdopcionTitle_adopcionAprobada}" />
                    <h:outputLabel value="#{bundle.CreateAdopcionLabel_adoptanteidAdoptante}" for="adoptanteidAdoptante" />
                    <h:selectOneMenu id="adoptanteidAdoptante" value="#{adopcionController.selected.adoptanteidAdoptante}" title="#{bundle.CreateAdopcionTitle_adoptanteidAdoptante}" required="true" requiredMessage="#{bundle.CreateAdopcionRequiredMessage_adoptanteidAdoptante}">
                        <f:selectItems value="#{adoptanteController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateAdopcionLabel_mascotasIdmascotas}" for="mascotasIdmascotas" />
                    <h:selectOneMenu id="mascotasIdmascotas" value="#{adopcionController.selected.mascotasIdmascotas}" title="#{bundle.CreateAdopcionTitle_mascotasIdmascotas}" required="true" requiredMessage="#{bundle.CreateAdopcionRequiredMessage_mascotasIdmascotas}">
                        <f:selectItems value="#{mascotasController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{adopcionController.create}" value="#{bundle.CreateAdopcionSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{adopcionController.prepareList}" value="#{bundle.CreateAdopcionShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateAdopcionIndexLink}"/>
            </h:form>

    </body>
</html>

web/adopcion/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditAdopcionTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditAdopcionLabel_idadopcion}" for="idadopcion" />
                    <h:inputText id="idadopcion" value="#{adopcionController.selected.idadopcion}" title="#{bundle.EditAdopcionTitle_idadopcion}" required="true" requiredMessage="#{bundle.EditAdopcionRequiredMessage_idadopcion}"/>
                    <h:outputLabel value="#{bundle.EditAdopcionLabel_resultado}" for="resultado" />
                    <h:inputText id="resultado" value="#{adopcionController.selected.resultado}" title="#{bundle.EditAdopcionTitle_resultado}" required="true" requiredMessage="#{bundle.EditAdopcionRequiredMessage_resultado}"/>
                    <h:outputLabel value="#{bundle.EditAdopcionLabel_adopcionAprobada}" for="adopcionAprobada" />
                    <h:inputText id="adopcionAprobada" value="#{adopcionController.selected.adopcionAprobada}" title="#{bundle.EditAdopcionTitle_adopcionAprobada}" />
                    <h:outputLabel value="#{bundle.EditAdopcionLabel_adoptanteidAdoptante}" for="adoptanteidAdoptante" />
                    <h:selectOneMenu id="adoptanteidAdoptante" value="#{adopcionController.selected.adoptanteidAdoptante}" title="#{bundle.EditAdopcionTitle_adoptanteidAdoptante}" required="true" requiredMessage="#{bundle.EditAdopcionRequiredMessage_adoptanteidAdoptante}">
                        <f:selectItems value="#{adoptanteController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditAdopcionLabel_mascotasIdmascotas}" for="mascotasIdmascotas" />
                    <h:selectOneMenu id="mascotasIdmascotas" value="#{adopcionController.selected.mascotasIdmascotas}" title="#{bundle.EditAdopcionTitle_mascotasIdmascotas}" required="true" requiredMessage="#{bundle.EditAdopcionRequiredMessage_mascotasIdmascotas}">
                        <f:selectItems value="#{mascotasController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{adopcionController.update}" value="#{bundle.EditAdopcionSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditAdopcionViewLink}"/>
                <br />
                <h:commandLink action="#{adopcionController.prepareList}" value="#{bundle.EditAdopcionShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditAdopcionIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/adopcion/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <body>
        
        

            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListAdopcionEmpty}" rendered="#{adopcionController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{adopcionController.items.rowCount > 0}">
                    <h:outputText value="#{adopcionController.pagination.pageFirstItem + 1}..#{adopcionController.pagination.pageLastItem + 1}/#{adopcionController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{adopcionController.previous}" value="#{bundle.Previous} #{adopcionController.pagination.pageSize}" rendered="#{adopcionController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{adopcionController.next}" value="#{bundle.Next} #{adopcionController.pagination.pageSize}" rendered="#{adopcionController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{adopcionController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAdopcionTitle_idadopcion}"/>
                            </f:facet>
                            <h:outputText value="#{item.idadopcion}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAdopcionTitle_resultado}"/>
                            </f:facet>
                            <h:outputText value="#{item.resultado}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAdopcionTitle_adopcionAprobada}"/>
                            </f:facet>
                            <h:outputText value="#{item.adopcionAprobada}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAdopcionTitle_adoptanteidAdoptante}"/>
                            </f:facet>
                            <h:outputText value="#{item.adoptanteidAdoptante}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAdopcionTitle_mascotasIdmascotas}"/>
                            </f:facet>
                            <h:outputText value="#{item.mascotasIdmascotas}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{adopcionController.prepareView}" value="#{bundle.ListAdopcionViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{adopcionController.prepareEdit}" value="#{bundle.ListAdopcionEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{adopcionController.destroy}" value="#{bundle.ListAdopcionDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{adopcionController.prepareCreate}" value="#{bundle.ListAdopcionCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListAdopcionIndexLink}"/>
            </h:form>
    </body>

</html>

web/adopcion/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <body>
    
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewAdopcionLabel_idadopcion}"/>
                    <h:outputText value="#{adopcionController.selected.idadopcion}" title="#{bundle.ViewAdopcionTitle_idadopcion}"/>
                    <h:outputText value="#{bundle.ViewAdopcionLabel_resultado}"/>
                    <h:outputText value="#{adopcionController.selected.resultado}" title="#{bundle.ViewAdopcionTitle_resultado}"/>
                    <h:outputText value="#{bundle.ViewAdopcionLabel_adopcionAprobada}"/>
                    <h:outputText value="#{adopcionController.selected.adopcionAprobada}" title="#{bundle.ViewAdopcionTitle_adopcionAprobada}"/>
                    <h:outputText value="#{bundle.ViewAdopcionLabel_adoptanteidAdoptante}"/>
                    <h:outputText value="#{adopcionController.selected.adoptanteidAdoptante}" title="#{bundle.ViewAdopcionTitle_adoptanteidAdoptante}"/>
                    <h:outputText value="#{bundle.ViewAdopcionLabel_mascotasIdmascotas}"/>
                    <h:outputText value="#{adopcionController.selected.mascotasIdmascotas}" title="#{bundle.ViewAdopcionTitle_mascotasIdmascotas}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{adopcionController.destroyAndView}" value="#{bundle.ViewAdopcionDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewAdopcionEditLink}"/>
                <br />
                <h:commandLink action="#{adopcionController.prepareCreate}" value="#{bundle.ViewAdopcionCreateLink}" />
                <br />
                <h:commandLink action="#{adopcionController.prepareList}" value="#{bundle.ViewAdopcionShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewAdopcionIndexLink}"/>

            </h:form>

    </body>
</html>