src/java/Controller/AdopcionController.java
package Controller;

import Entity.Adopcion;
import Controller.util.JsfUtil;
import Controller.util.PaginationHelper;
import Entity.Usuario;
import Session.AdopcionFacade;

import org.primefaces.event.CloseEvent;
import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.servlet.http.HttpServletRequest;

@Named("adopcionController")
@SessionScoped
public class AdopcionController implements Serializable {

    private Adopcion current;
    private DataModel items = null;
    @EJB
    private Session.AdopcionFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public AdopcionController() {
    }

    public Adopcion getSelected() {
        if (current == null) {
            current = new Adopcion();
            selectedItemIndex = -1;
        }
        return current;
    }

    private AdopcionFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Adopcion) getItems().getRowData();
        //selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        selectedItemIndex= -1;
              System.out.println("Nombre "+getSelected().getMascotasIdmascotas().getNombre());
        return "sisexp/catalogo";
    }

    public String prepareCreate() {
//         current = new Adopcion();
         System.out.println(current.getAdoptanteidAdoptante().getUsuarioIdusuario().getNombre());
//        selectedItemIndex = -1;
        Usuario usuario = (Usuario) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("usuario");
        System.out.println(usuario.getIdusuario());
        System.out.println(getSelected().getMascotasIdmascotas().getNombre());
        
        return "expedientes/Create";
    }

    public void metodo(){
        Usuario usuario = (Usuario) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("usuario");
        System.out.println(usuario.getIdusuario());
        System.out.println(getSelected().getMascotasIdmascotas().getNombre());
        
    }
    
    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AdopcionCreated"));
//            String nombreadoptante = current.getAdoptanteidAdoptante()

            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Adopcion) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AdopcionUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Adopcion) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AdopcionDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Adopcion getAdopcion(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Adopcion.class)
    public static class AdopcionControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            AdopcionController controller = (AdopcionController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "adopcionController");
            return controller.getAdopcion(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Adopcion) {
                Adopcion o = (Adopcion) object;
                return getStringKey(o.getIdadopcion());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Adopcion.class.getName());
            }
        }

    }

    public boolean Adoptado(int i) {

        return i == 1;
    }

    public void AdoptaSelect() {

        current = (Adopcion) getItems().getRowData();
        System.out.println("Select");
        System.out.println(current.getResultado());
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        System.out.println(selectedItemIndex);

    }

    public String Adopta() {

        addMessage("Mascota en Adopcion:  Adopcion Registrada", "Adopcion Registrada");
        current = (Adopcion) getItems().getRowData();
        System.out.println(current.getResultado());
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        System.out.println(selectedItemIndex);
        current.setAdopcionAprobada(1);
        try {
            getFacade().edit(current);

        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }

        return "admin";
    }

    public void addMessage(String summary, String detail) {
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, summary, detail);
        FacesContext.getCurrentInstance().addMessage(null, message);

    }

}

src/java/Controller/UsuarioController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controller;

import Controller.util.JsfUtil;
import Entity.Adoptante;
import Entity.Usuario;
import Entity.Veterinario;
import Session.AdoptanteFacade;
import Session.UsuarioFacadeLocal;
import Session.VeterinarioFacade;
import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.inject.Named;

/**
 *
 * @author chef
 */
@Named
@SessionScoped
public class UsuarioController implements Serializable {

    @EJB
    private UsuarioFacadeLocal userEJB;
    
    @EJB
    private VeterinarioFacade vetEJB;
    
    @EJB
    private AdoptanteFacade adoptanteEJB;
    
    private Usuario User;
    private Veterinario vet;
    private Adoptante adopta;

    @PostConstruct
    public void init() {
        User = new Usuario();
        vet = new Veterinario();
        adopta = new Adoptante();
    }

    /**
     * @return the User
     */
    public Usuario getUser() {
        return User;
    }

    /**
     * @param User the User to set
     */
    public void setUser(Usuario User) {
        this.User = User;
    }

    public void registrarveterinario() {
        try {
            User.setRol(1);
            this.vet.setUsuarioIdusuario(User);
            vetEJB.create(vet);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Aviso:", "Usuario Registrado"));
            System.out.println("Se registro");
        } catch (Exception e) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Aviso", "Usuario No registrado"));
        }
    }
    public String registraruser() {
        try {
            User.setRol(2);
            this.adopta.setUsuarioIdusuario(User);
            adoptanteEJB.create(adopta);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Aviso:", "Usuario Registrado"));
            System.out.println("Se registro");
            User = new Usuario();
        } catch (Exception e) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Aviso", "Usuario No registrado"));
        }return "/index";
    }

    public String iniciarSession() {
        String redireccion = null;
        Usuario us;
        try {
            us = userEJB.iniciarsession(User);
            if (us != null) {
                if (us.getRol() == 1) {
                    FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("usuario", us);
                    redireccion = "/expedientes/List?faces-redirect=true";
                }else if (us.getRol() == 0) {
                    FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("usuario", us);
                    redireccion = "/Admin/admin?faces-redirect=true";
                }
                else if(us.getRol()==2) {
                    FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("usuario", us);
                    redireccion = "/sisexp/catalogo?faces-redirect=true";
                }

            } else {
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, "Aviso", "Usuario con credenciales Incorrectas"));
            }
        } catch (Exception e) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, "Aviso", "Error:"));
        }
        return redireccion;
    }

    public void VerificarSession() {
        try {
            Usuario us = (Usuario) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("usuario");
            if (us == null) {
                FacesContext.getCurrentInstance().getExternalContext().redirect("/index.xhtml");
            }
        } catch (Exception e) {
        }
    }

    public void VerificarSessionVeterinario() {
        try {
            Usuario us = (Usuario) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("usuario");
            if (us == null||us.getRol()!=1) {
                FacesContext.getCurrentInstance().getExternalContext().redirect("/index.xhtml");
            } 
        } catch (Exception e) {
        }
    }
    public void VerificarSessionAdmin() {
        try {
            Usuario us = (Usuario) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("usuario");
            if (us == null||us.getRol()!=0) {
                FacesContext.getCurrentInstance().getExternalContext().redirect("./../index.xhtml");
            } 
        } catch (Exception e) {
        }
    }
    public void VerificarSessionUsuario() {
        try {
            Usuario us = (Usuario) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("usuario");
            if (us == null||us.getRol()!=2) {
                FacesContext.getCurrentInstance().getExternalContext().redirect("./../index.xhtml");
            } 
        } catch (Exception e) {
        }
    }

     public String cerrarSession() {
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
        return "/index.xhtml";
    }
     
    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(userEJB.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(userEJB.findAll(), true);
    }

    /**
     * @return the vet
     */
    public Veterinario getVet() {
        return vet;
    }

    /**
     * @param vet the vet to set
     */
    public void setVet(Veterinario vet) {
        this.vet = vet;
    }

    /**
     * @return the adopta
     */
    public Adoptante getAdopta() {
        return adopta;
    }

    /**
     * @param adopta the adopta to set
     */
    public void setAdopta(Adoptante adopta) {
        this.adopta = adopta;
    }
}

web/Admin/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">



    <ui:composition template="./../Templates/templateamdmin.xhtml">

        <ui:define name="title">
            <h:outputText value="#{bundle.CreateMascotasTitle}"></h:outputText>
        </ui:define>

        <ui:define name="content">
            <h:form id="formmascota">
                <p:growl id="growl" life="2000" />
                <h:panelGrid id="panel1" columns="3" >

                    <p:outputLabel value="#{bundle.CreateMascotasLabel_nombre}" for="nombre" />
                    <p:inputText id="nombre" value="#{mascotasController.selected.nombre}" title="#{bundle.CreateMascotasTitle_nombre}" required="true" requiredMessage="Se requiere un nombre"/>
                    <p:message for="nombre"/>
                    <p:outputLabel value="#{bundle.CreateMascotasLabel_especie}" for="especie" />
                    <p:selectOneMenu id="especie" value="#{mascotasController.selected.especie}"   required="true" style="width: 165px;">
                        <f:selectItem itemValue="Perro" itemLabel="Perro" />
                        <f:selectItem itemValue="Gato" itemLabel="Gato" />
                    </p:selectOneMenu>
                    <p:message for="especie"/>
                    <p:outputLabel value="#{bundle.CreateMascotasLabel_raza}" for="raza" />
                    <p:inputText id="raza" value="#{mascotasController.selected.raza}" title="#{bundle.CreateMascotasTitle_raza}" required="true" requiredMessage="Se requiere una raza"/>
                    <p:message for="raza"/>
                    <p:outputLabel value="#{bundle.CreateMascotasLabel_tamanio}" for="tamanio" /> 
                    <p:selectOneMenu id="tamanio" value="#{mascotasController.selected.tamanio}"   required="true" requiredMessage="#{bundle.CreateMascotasRequiredMessage_tamanio}" style="width: 165px;">
                        <f:selectItem itemValue="0" itemLabel="Pequeño" />
                        <f:selectItem itemValue="1" itemLabel="Mediano" />
                        <f:selectItem itemValue="2" itemLabel="Grande" />
                    </p:selectOneMenu>
                    <p:message for="tamanio"/>
                    <p:outputLabel value="#{bundle.CreateMascotasLabel_descripcion}" for="descripcion" />
                    <p:inputText id="descripcion" value="#{mascotasController.selected.descripcion}" title="#{bundle.CreateMascotasTitle_descripcion}" required="true" requiredMessage="Se requiere de una descripcion de la personalidad de la"/>
                    <p:message for="descripcion"/>
                    <p:outputLabel value="#{bundle.CreateMascotasLabel_foto}" for="foto" />
                    <p:inputText id="foto" value="#{mascotasController.selected.foto}" title="#{bundle.CreateMascotasTitle_foto}" required="true" requiredMessage="Se requiere del nombre de la foto que se usara"/>
                    <p:message for="foto"/>
                    <p:outputLabel value="#{bundle.CreateMascotasLabel_sexo}" for="sexo" />
                    <p:selectOneMenu id="sexo" value="#{mascotasController.selected.sexo}"   required="true" style="width: 165px;" >
                        <f:selectItem itemValue="M" itemLabel="M" />
                        <f:selectItem itemValue="F" itemLabel="F" />
                    </p:selectOneMenu>
                    <p:message for="sexo"/>
                    <p:outputLabel value="#{bundle.CreateMascotasLabel_color}" for="color" />
                    <p:inputText id="color" value="#{mascotasController.selected.color}" title="#{bundle.CreateMascotasTitle_color}" required="true" requiredMessage="Se requiere el color de la mascota"/>
                    <p:message for="color"/>
                    <p:outputLabel value="Señas Particulares" for="SParticulares" />
                    <p:inputText id="SParticulares" value="#{mascotasController.selected.SParticulares}" title="#{bundle.CreateMascotasTitle_SParticulares}" required="true" requiredMessage="Se requieren señas particulares de la masctoa"/>
                    <p:message for="SParticulares"/>
                    <p:outputLabel value="Fecha de Nacimiento" for="fechaNacimiento" />
                    <p:calendar id="fechaNacimiento" pattern="MM/dd/yyyy" value="#{mascotasController.selected.fechaNacimiento}" title="#{bundle.EditMascotasTitle_fechaNacimiento}" required="true"  showOn="button" requiredMessage="Se requiere de la fecha de nacimiento de la mascota" />
                    <p:message for="fechaNacimiento"/>
                </h:panelGrid>
                
                <p:commandButton icon="ui-icon-disk"  action="#{mascotasController.create()}"  ajax="false" update="growl" value="Guardar" />
                <p:spacer width="25px"/>
                <p:button value="Reiniciar" icon="ui-icon-radio-off" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/Admin/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <ui:composition template="./../Templates/templateamdmin.xhtml">
        <ui:define name="title">
            <h:outputText value="Lista de Adopciones"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <h:form >
                

                <h:outputText escape="false" value="#{bundle.ListAdopcionEmpty}" rendered="#{adopcionController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{adopcionController.items.rowCount > 0}">
                    <h:outputText value="#{adopcionController.pagination.pageFirstItem + 1}..#{adopcionController.pagination.pageLastItem + 1}/#{adopcionController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{adopcionController.previous}" value="#{bundle.Previous} #{adopcionController.pagination.pageSize}" rendered="#{adopcionController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{adopcionController.next}" value="#{bundle.Next} #{adopcionController.pagination.pageSize}" rendered="#{adopcionController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{adopcionController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 3px; text-align: center">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Adoptante"/>
                            </f:facet>
                            <h:outputText value="#{item.adoptanteidAdoptante.usuarioIdusuario.nombre}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Mascota"/>
                            </f:facet>
                            <h:outputText value="#{item.mascotasIdmascotas.nombre}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Resultado"/>
                            </f:facet>
                            <h:outputText value="#{item.resultado}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Evaluacion Aprobada"/>
                            </f:facet>
                            
                            <p:selectBooleanCheckbox value="#{adopcionController.Adoptado(item.adopcionAprobada)}" disabled="true" />
                        </h:column>
                        <h:column>
                            <p:growl id="growl" life="2000" />
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            -
                            <p:commandButton ajax="false" icon="ui-icon-circle-check" value="Aprobar" action="#{adopcionController.Adopta()}" update="growl"  disabled="#{adopcionController.Adoptado(item.adopcionAprobada)}"/>
                            -
                        </h:column>
                    </h:dataTable>

                </h:panelGroup>


            </h:form>

            <p:dialog id="dialogo1" widgetVar="adopdialog" header="confirmacion">

                <h:form id="Adoptform" >
                    
                    <h:panelGroup id="display" >
                        <p:panelGrid columns="2" >
                            <h:outputText value="Nombre Completo del Adoptante"/>
                            <h:outputText value="#{adopcionController.selected.adoptanteidAdoptante.usuarioIdusuario.nombre}" title="#{bundle.ViewAdopcionTitle_idadopcion}"/>
                            <h:outputText value="Mascota que desea Adoptar"/>
                            <h:outputText value="#{adopcionController.selected.mascotasIdmascotas.nombre}" title="#{bundle.ViewAdopcionTitle_resultado}"/>
                            <h:outputText value="Direccion del Adoptante"/>
                            <h:outputText value="#{adopcionController.selected.adoptanteidAdoptante.usuarioIdusuario.direccion}" title="#{bundle.ViewAdopcionTitle_adopcionAprobada}"/>
                            <h:outputText value="Resultado del Sistema"/>
                            <h:outputText value="#{adopcionController.selected.resultado}" title="#{bundle.ViewAdopcionTitle_adoptanteidAdoptante}"/>
                        </p:panelGrid>
                        
                    </h:panelGroup>
                    
                    <p:commandButton value="Cerrar" onclick="adopdialog.hide()"/>
                </h:form>

            </p:dialog>

        </ui:define>
    </ui:composition>

</html>

web/Admin/registrarvet.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="./../Templates/templateamdmin.xhtml">
        
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateMascotasTitle}"></h:outputText>
        </ui:define>
        
        <ui:define name="content">
        <h:form>
            <p:growl id="mensaje" autoUpdate="true" showDetail="true"/>

                <h:panelGrid columns="3" id="datosuser">
                    <p:outputLabel for="nombre" value="Nombre:"/>
                    <p:inputText id="nombre" value="#{usuarioController.user.nombre}" required="true"/>
                    <p:message for="nombre"/>
                    <p:outputLabel for="correo" value="Correo:"/>
                    <p:inputText id="correo" value="#{usuarioController.user.email}" required="true"/>
                    <p:message for="correo"/>
                    <p:outputLabel for="pass1" value="Contraseña:"/>
                    <p:password id="pass1" value="#{usuarioController.user.password}" required="true" match="pass2" feedback="true" promptLabel="Ingrese una Caontraseña"/>
                    <p:message for="pass1"/>
                    <p:outputLabel for="pass2" value="Repetir Contraseña:"/>
                    <p:password id="pass2" required="true"/>
                    <p:message for="pass2"/>
                    <p:outputLabel for="user" value="Usuario"/>
                    <p:inputText id="user" value="#{usuarioController.user.usuario}" required="true" />
                    <p:message for="user"/>
                    <p:outputLabel for="vet" value="Cedula Prof."/>
                    <p:inputText id="vet" value="#{usuarioController.vet.cedulaProfecional}" required="true"/>
                    <p:message for="vet"/>
                    <p:outputLabel for="tel" value="Telfono:"/>
                    <p:inputText id="tel"  value="#{usuarioController.user.telefono}" required="true"/>
                    <p:message for="tel"/>
                    <p:outputLabel for="dom" value="Domicilio"/>
                    <p:inputTextarea id="dom" value="#{usuarioController.user.direccion}" required="true"/>
                    <p:message for="dom"/>
                    <p:column/>
                    <p:commandButton icon="ui-icon-check" value="Registrar" update="datosuser,mensaje" actionListener="#{usuarioController.registrarveterinario()}"/>
                </h:panelGrid>

        </h:form>
     </ui:define>
    </ui:composition>

</html>